### ISSUE TITLE
Update fks-initBL.sh

### ISSUE THREAD

**Issue by Auratons** [fykosak/fks-scripts#1]
Tento skript nevyplní v problemX-Y.tex \probbatch{}, \probno{}, \probsource{} podle složky, ve které se volal. Třeba vyřešit.

**Comment by LukasLedvina** [comment]
\probsource by ideálně vyplňovat neměl (alespoň ve fykosu), protože podle vyplnění tohoto políčka se pozná, zdali byla úloha importována z fykos-ulohy.

**Comment by LukasLedvina** [comment]
Fixed. Prosím o merge:
- fks-templates: dev: e0ec081
- fks-scripts? dev: ea689ad

**Comment by Werkov** [comment]
fks-templates jsem mergeoval a publikoval (fks-templates_1.3-29-ge0ec081).

fks-scripts: Jaká je sémantika toho prázdného `probsource`? Bez ohledu na import by měly úlohy v sérii mít jako zdroj FYKOS, ne?

**Comment by LukasLedvina** [comment]
`probsource` se při inicializaci vyplňuje pouze pro výfuk. Pro fykos se pri inicializaci nevyplňuje a vyplní se až při importu z `fykos-ulohy`. Je to proto, aby se dalo identifikovat, zdali již došlo k importu.

**Comment by Werkov** [comment]
OK, přidal zadokumentoval jsem to a releasnul.

fks-scripts_1.1-31-gd37e44f
